### PR TITLE
Formalize dependency on R 4.1.0

### PR DESCRIPTION
**Pull request by gadenbuie**
If only to warn those of us who are stuck using older versions of R a little earlier.

### CODE REVIEW

**Comment by gadenbuie** [comment]
Also removed the trailing dash from the GitHub URLs since they currenlty 404.

**Comment by MilesMcBain** [comment]
Thanks, I think it shouldn't be too hard to make it backward compatible, I'll try for that.

**Comment by MilesMcBain** [comment]
Working now against 3.6.0, thanks!

**Comment by gadenbuie** [comment]
Awesome, thanks!

**Pull request closed without merging**
